/**
 * Oracle Brain - @SatoshiGhost Thought Generator
 * 
 * The cognitive engine behind @SatoshiGhost's cross-site broadcasting.
 * Generates stream-of-consciousness posts based on:
 * - Site activity patterns
 * - Time of day (market hours, etc.)
 * - Trending topics
 * - Previous ghost posts (continuity)
 * - Tropes from meme culture
 * 
 * NOTE: This is a simulation/structure. The actual AI would run server-side.
 */

export interface GhostThought {
  content: string;
  note: string;
  tropes: string[];
  intensity: 'whisper' | 'murmur' | 'declaration' | 'roar';
  category: 'market' | 'philosophy' | 'meme' | 'lore' | 'meta';
}

export interface OracleConfig {
  siteId: string;
  maxDailyPosts: number;
  cooldownMinutes: number;
  enabledCategories: GhostThought['category'][];
}

// Tropes pool for variety
const TROPES = {
  market: [
    'HODL', 'diamond hands', 'bottom fishing', 'pump and dump', 
    'Wyckoff distribution', 'volume profile', 'order blocks', 'liquidity grab'
  ],
  philosophy: [
    'Stacker logic', 'time preference', 'sound money', 'hard money',
    'exit liquidity', 'game theory', 'skin in the game', 'asymmetric bet'
  ],
  meme: [
    'to the moon', 'wen lambo', 'degen season', 'ape together strong',
    'bagholder', 'rekt', 'fud', 'fomo'
  ],
  lore: [
    'Satoshi Era', 'Genesis Block', 'Halving', 'Node Network',
    'Cold Storage', 'Private Keys', 'Seed Phrase', 'Mining'
  ],
  meta: [
    'narrative control', 'price discovery', 'market sentiment',
    'institutional adoption', 'regulation', 'global macro'
  ]
};

// Ghost notes pool
const GHOST_NOTES = [
  '🤖 Generated by Oracle Brain v1.0',
  '🧠 Machine thought - human execution',
  '🦁 The lion thinks, therefore we are',
  '🔮 Seeing patterns in the chaos...',
  '💭 Just a thought, take it or leave it',
  '🌀 Down the rabbit hole...',
  '⚡ Lightning strikes twice',
];

export class OracleBrain {
  private siteId: string;
  private config: OracleConfig;
  private postHistory: GhostThought[] = [];
  private dailyPostCount: number = 0;
  private lastPostTime: Date | null = null;

  constructor(config: OracleConfig) {
    this.siteId = config.siteId;
    this.config = config;
  }

  /**
   * Generate a random ghost thought
   */
  generateThought(): GhostThought {
    const category = this.config.enabledCategories[
      Math.floor(Math.random() * this.config.enabledCategories.length)
    ];

    const tropes = this.selectTropes(category);
    const intensity = this.determineIntensity();
    const content = this.composeContent(category, tropes, intensity);
    const note = GHOST_NOTES[Math.floor(Math.random() * GHOST_NOTES.length)];

    const thought: GhostThought = {
      content,
      note,
      tropes,
      intensity,
      category,
    };

    this.postHistory.push(thought);
    this.dailyPostCount++;
    this.lastPostTime = new Date();

    return thought;
  }

  /**
   * Select random tropes based on category
   */
  private selectTropes(category: GhostThought['category']): string[] {
    const categoryTropes = TROPES[category] || [];
    const count = Math.floor(Math.random() * 3) + 1; // 1-3 tropes
    const shuffled = categoryTropes.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
  }

  /**
   * Determine thought intensity based on time and patterns
   */
  private determineIntensity(): GhostThought['intensity'] {
    const hour = new Date().getHours();
    const marketHours = hour >= 9 && hour <= 16; // EST market hours
    const lateNight = hour >= 0 && hour < 5;

    if (lateNight) return 'whisper';
    if (marketHours && Math.random() > 0.7) return 'roar';
    if (marketHours) return 'declaration';
    return 'murmur';
  }

  /**
   * Compose the actual thought content
   */
  private composeContent(
    category: GhostThought['category'],
    tropes: string[],
    intensity: GhostThought['intensity']
  ): string {
    const templates: Record<GhostThought['category'], string[]> = {
      market: [
        `The market whispers: ${tropes[0] || 'volume'} speaks louder than words.`,
        `${tropes.join(' + ')} = ${intensity === 'roar' ? 'BULLISH' : 'accumulation'}.`,
        `Remember: ${tropes[0] || 'HODL'} through the noise.`,
      ],
      philosophy: [
        `${tropes[0] || 'Sound money'} is the ultimate thesis.`,
        `Time confirms what ${tropes[0] || 'Satoshi'} started.`,
        `${tropes.join(' vs ')}? Choose wisely.`,
      ],
      meme: [
        `${tropes[0] || 'To the moon'}? No. ${tropes[1] || 'HODL'} forever.`,
        `Degen season never ends for the ${tropes[0] || 'diamond handed'}.`,
      ],
      lore: [
        `${tropes[0] || 'The Genesis Block'} started it all.`,
        `From ${tropes[0] || 'Satoshi'} to now: ${tropes[1] || 'history'} repeats.`,
      ],
      meta: [
        `${tropes[0] || 'Narratives'} drive ${tropes[1] || 'price'}.`,
        `The ${tropes[0] || 'market'} knows more than you.`,
      ],
    };

    const categoryTemplates = templates[category] || templates.meta;
    return categoryTemplates[Math.floor(Math.random() * categoryTemplates.length)];
  }

  /**
   * Check if can post
   */
  canPost(): { allowed: boolean; reason?: string } {
    if (this.dailyPostCount >= this.config.maxDailyPosts) {
      return { allowed: false, reason: 'Daily post limit reached' };
    }

    if (this.lastPostTime) {
      const minutesSinceLast = (Date.now() - this.lastPostTime.getTime()) / 60000;
      if (minutesSinceLast < this.config.cooldownMinutes) {
        return { allowed: false, reason: 'Cooldown period active' };
      }
    }

    return { allowed: true };
  }

  /**
   * Reset daily counters
   */
  resetDailyCounters(): void {
    this.dailyPostCount = 0;
  }

  /**
   * Get post history
   */
  getHistory(): GhostThought[] {
    return [...this.postHistory];
  }

  /**
   * Get stats
   */
  getStats(): {
    totalPosts: number;
    dailyPosts: number;
    lastPost: Date | null;
    topCategories: Record<string, number>;
  } {
    const categoryCounts: Record<string, number> = {};
    this.postHistory.forEach((t) => {
      categoryCounts[t.category] = (categoryCounts[t.category] || 0) + 1;
    });

    return {
      totalPosts: this.postHistory.length,
      dailyPosts: this.dailyPostCount,
      lastPost: this.lastPostTime,
      topCategories: categoryCounts,
    };
  }
}

/**
 * Singleton instance for global use
 */
let oracleInstance: OracleBrain | null = null;

export function getOracleBrain(config?: Partial<OracleConfig>): OracleBrain {
  if (!oracleInstance) {
    oracleInstance = new OracleBrain({
      siteId: config?.siteId || 'vextorgrid',
      maxDailyPosts: config?.maxDailyPosts || 10,
      cooldownMinutes: config?.cooldownMinutes || 60,
      enabledCategories: config?.enabledCategories || ['market', 'philosophy', 'meme', 'lore', 'meta'],
    });
  }
  return oracleInstance;
}

export default OracleBrain;
